[package]
name = "day-5"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
couleur = "0.1.0"
ez_colorize = "0.1.0"
